type Restaurant = {
    name: string;
    categories: Category[];
    location: Location;
    menu: string;
}

type Category = 'drinks' | 'fancy' | 'weekend' | 'tiki drinks' | 'brewery' | 'kid friendly' | 'dog friendly' | 'patio'
| 'burgers' | 'southern' | 'sandwiches' | 'american' | 'seafood' | 'pizza' | 'quick/casual' | 'italian' | 'happy hour food'
| 'japanese' | 'frozen drinks' | 'mexican' | 'bbq' | 'asian' | 'french' | 'mediterranean' | 'thai' | 'chinese'
| 'foodtruck' | 'indian' | 'vietnamese' | 'korean'

type Location = 'North' | 'Central' | 'South 1st/Lamar' | 'East Side' | 'Downtown' | 'West' | 'South' | 'Cedar Park';

const restaurants: Restaurant[] = [
    {name: "Perry's Steakhouse", categories: ['drinks', 'fancy'], location: 'North', menu: 'https://perryssteakhouse.com/locations/tx/austin/domain-northside/#'},
    {name: "Tiki Tatsu-Ya", categories: ['drinks', 'weekend', 'tiki drinks'], location: 'South 1st/Lamar', menu: 'https://www.tiki-tatsuya.com/menu-qr'},
    {name: "Here Nor There", categories: ['drinks', 'weekend'], location: 'Downtown', menu: 'http://hntaustin.com/'},
    {name: "Slackers", categories: ['drinks', 'brewery', 'kid friendly'], location: 'North', menu: 'https://www.slackersbrewing.com/'},
    {name: "Pour House", categories: ['drinks', 'pizza', 'dog friendly', 'kid friendly', 'patio'], location: 'North', menu: 'http://pourhousepintsandpies.com/menu.pdf'},
    {name: "The Dig Pub", categories: ['drinks'], location: 'North', menu: 'https://www.thedigpub.com/dining'},
    {name: "Prohibition", categories: ['drinks', 'weekend'], location: 'North', menu: 'http://www.prohibition-atx.com/'},
    {name: "Bosses Office", categories: ['drinks', 'weekend', 'fancy'], location: 'East Side', menu: 'https://bossesofficeaustin.com/'},
    {name: "Whip My Soul", categories: ['southern'], location: 'North', menu: 'https://www.instagram.com/whipmysoul/?hl=en'},
    {name: "Garbos", categories: ['seafood', 'tiki drinks'], location: 'North', menu: 'http://garboslobsteratx.com/'},
    {name: "Jewboy Burgers", categories: ['burgers', 'dog friendly', 'patio'], location: 'Central', menu: 'http://www.jewboyburgers.com/'},
    {name: "Otherside Deli", categories: ['sandwiches'], location: 'Central', menu: 'hhttp://othersidedeliatx.com/'},
    {name: "Sour Duck Market", categories: ['american', 'dog friendly', 'patio'], location: 'East Side', menu: 'http://sourduckmarket.com/'},
    {name: "Birdie's", categories: ['american', 'fancy'], location: 'East Side', menu: 'https://www.birdiesaustin.com/menus/#dinner'},
    {name: "Anything's Baked Potato", categories: ['quick/casual'], location: 'East Side', menu: 'http://www.anythingsaustin.com/'},
    {name: "Ike's Love & Sandwiches", categories: ['sandwiches', 'quick/casual'], location: 'North', menu: 'https://locations.ikessandwich.com/tx/austin/419/'},
    {name: "Foxhold Culinary Tavern", categories: ['american', 'fancy'], location: 'North', menu: 'http://www.foxholeaustin.com/wp-content/uploads/2020/05/2020-Foxhole-Spring-Menu.pdf'},
    {name: "Bon Aire", categories: ['american'], location: 'North', menu: 'https://www.bonaireatx.com/menu'},
    {name: "Juliet", categories: ['italian', 'fancy', 'happy hour food'], location: 'North', menu: 'https://www.juliet-austin.com/arboretum-menu'},
    {name: "Roaring Fork", categories: ['american', 'fancy'], location: 'North', menu: 'http://www.foxholeaustin.com/wp-content/uploads/2020/05/2020-Foxhole-Spring-Menu.pdf'},
    {name: "Uchibā", categories: ['japanese', 'fancy', 'happy hour food'], location: 'Downtown', menu: 'https://uchiba.uchirestaurants.com/'},
    {name: "Hanks", categories: ['american', 'happy hour food', 'frozen drinks', 'dog friendly'], location: 'East Side', menu: 'https://www.hanksaustin.com/menus'},
    {name: "Bulevar", categories: ['mexican', 'fancy', 'happy hour food'], location: 'North', menu: 'https://www.bulevaratx.com/'},
    {name: "Salty Sow", categories: ['american', 'fancy', 'happy hour food'], location: 'Central', menu: 'http://www.saltysow.com/'},
    {name: "Loro", categories: ['japanese', 'fancy', 'bbq', 'happy hour food'], location: 'South 1st/Lamar', menu: 'http://loroaustin.com/'},
    {name: "Uchiko", categories: ['japanese', 'fancy', 'happy hour food'], location: 'Central', menu: 'https://uchikoaustin.com/wp-content/uploads/Uchiko_To_Go.pdf'},
    {name: "Peached Tortilla", categories: ['asian', 'fancy', 'happy hour food'], location: 'North', menu: 'http://www.thepeachedtortilla.com/'},
    {name: "Justine's", categories: ['french', 'fancy'], location: 'East Side', menu: 'https://www.justines1937.com/'},
    {name: "Comedor", categories: ['mexican', 'fancy'], location: 'Downtown', menu: 'https://comedortx.com/'},
    {name: "Nomade", categories: ['mexican', 'fancy'], location: 'South 1st/Lamar', menu: 'https://www.nomadecocina.com/'},
    {name: "Lutie's", categories: ['american', 'fancy'], location: 'Central', menu: 'https://www.luties.com/'},
    {name: "Lenoir", categories: ['french', 'american', 'fancy'], location: 'South 1st/Lamar', menu: 'https://www.lenoirrestaurant.com/menu'},
    {name: "Honey Moon Spirit Lounge", categories: ['american', 'fancy'], location: 'Central', menu: 'http://www.honeymoonatx.com/'},
    {name: "gràcia mediterranean", categories: ['mediterranean', 'fancy'], location: 'North', menu: 'http://www.graciamediterranean.com/'},
    {name: "Yamas Greek", categories: ['mediterranean', 'fancy'], location: 'West', menu: 'http://www.yamasatx.com/'},
    {name: "Soupleaf Hotpot", categories: ['asian'], location: 'Central', menu: 'http://soupleafhotpot.com/'},
    {name: "Kiin Di", categories: ['thai', 'asian'], location: 'South 1st/Lamar', menu: 'https://www.kiindiatx.com/'},
    {name: "Jade Restaurant", categories: ['chinese', 'asian'], location: 'West', menu: 'http://www.jaderestaurantaustin.com/'},
    {name: "Bunboy", categories: ['asian', 'foodtruck'], location: 'North', menu: 'http://bunboyaustin.com/'},
    {name: "Banh Mi Galang", categories: ['vietnamese', 'asian'], location: 'North', menu: 'https://www.banhmigalang.com/'},
    {name: "Hot Pot Alley", categories: ['asian'], location: 'North', menu: 'https://www.hotpotalley.com/'},
    {name: "Sunflower", categories: ['vietnamese', 'asian'], location: 'North', menu: 'https://www.sunflowerrestaurants.com/'},
    {name: "Zoé Tong", categories: ['chinese', 'asian'], location: 'South 1st/Lamar', menu: 'https://www.zoetong.com/'},
    {name: "Fat Dragon", categories: ['chinese', 'asian'], location: 'North', menu: 'http://fatdragonatx.com/'},
    {name: "Din Ho", categories: ['chinese', 'asian'], location: 'North', menu: 'http://www.dinhochinesebbq.com/'},
    {name: "Wu Chow", categories: ['chinese', 'asian', 'fancy'], location: 'North', menu: 'https://www.wuchowaustin.com/north-lamar-menu/'},
    {name: "Lotus Chinese", categories: ['chinese', 'asian'], location: 'North', menu: 'http://www.lotuschineseatx.com/'},
    {name: "Giovanni's Table", categories: ['italian'], location: 'South', menu: 'https://giovannistable.com/'},
    {name: "Slapbox", categories: ['pizza', 'quick/casual', 'kid friendly', 'dog friendly'], location: 'North', menu: 'https://parmer.600degreespizzeria.com/'},
    {name: "Boss Pizza", categories: ['pizza', 'quick/casual'], location: 'North', menu: 'http://www.bosspizza.co/'},
    {name: "Tony C's Pizza", categories: ['pizza', 'quick/casual'], location: 'North', menu: 'https://www.tonycsbeergarden.com/'},
    {name: "Desano", categories: ['pizza', 'quick/casual'], location: 'North', menu: 'http://www.desanopizza.com/'},
    {name: "Conan's Pizza", categories: ['pizza', 'quick/casual'], location: 'North', menu: 'http://conanspizza.com/'},
    {name: "Cedro", categories: ['italian', 'fancy'], location: 'North', menu: 'https://www.cedroaustin.com/menu'},
    {name: "Sammie's", categories: ['italian', 'fancy'], location: 'Downtown', menu: 'https://sammiesitalian.com/'},
    {name: "Patrizi's", categories: ['italian', 'dog friendly', 'foodtruck'], location: 'Central', menu: 'http://patrizis.com/'},
    {name: "The Backspace", categories: ['pizza'], location: 'North', menu: 'http://backspacepizza.com/'},
    {name: "Pedrosos", categories: ['pizza', 'foodtruck'], location: 'North', menu: 'http://pedrosospizza.com/'},
    {name: "Rosati's", categories: ['pizza'], location: 'Cedar Park', menu: 'https://myrosatis.com/cedarpark/'},
    {name: "Curry Pizza House", categories: ['pizza'], location: 'Cedar Park', menu: 'https://www.currypizzahouse.com/'},
    {name: "i Fratelli", categories: ['pizza'], location: 'North', menu: 'https://www.ifratellipizza.com/'},
    {name: "Aviator Pizza", categories: ['pizza', 'patio', 'dog friendly', 'kid friendly'], location: 'North', menu: 'http://www.aviatorpizza.com/'},
    {name: "Lucky Robot", categories: ['japanese'], location: 'South 1st/Lamar', menu: 'https://www.luckyrobotatx.com/'},
    {name: "Kane", categories: ['japanese'], location: 'Cedar Park', menu: 'http://kanerestaurants.com/'},
    {name: "Miyo", categories: ['japanese'], location: 'North', menu: 'https://www.miyoatx.com/'},
    {name: "Zen", categories: ['japanese', 'quick/casual'], location: 'North', menu: 'https://www.eatzen.com/'},
    {name: "Soto", categories: ['japanese', 'fancy'], location: 'North', menu: 'http://www.sotoaustin.com/?y_source=1_MTYyMDc1MzMtNzE1LWxvY2F0aW9uLndlYnNpdGU%3D'},
    {name: "Kanji Ramen", categories: ['japanese'], location: 'North', menu: 'http://www.kanjiramen.com/'},
    {name: "Michi Ramen", categories: ['japanese'], location: 'North', menu: 'http://michiramen.com/'},
    {name: "Haru", categories: ['japanese'], location: 'North', menu: 'https://ichiumisushitx.com/menu/18710912'},
    {name: "Ramen Tatsu-Ya", categories: ['japanese'], location: 'North', menu: 'https://www.ramen-tatsuya.com/'},
    {name: "Kobako Katsu (Hmart)", categories: ['japanese'], location: 'North', menu: 'https://kobakokatsuaustin.com/'},
    {name: "Don Don Express", categories: ['japanese'], location: 'North', menu: 'https://dondonexpress.com/'},
    {name: "Nori", categories: ['japanese'], location: 'Central', menu: 'http://www.noriaustin.com/'},
    {name: "Ramen512", categories: ['japanese'], location: 'Cedar Park', menu: 'http://ramen512.com/'},
    {name: "Sazan Ramen", categories: ['japanese'], location: 'Central', menu: 'http://sazanramen.com/'},
    {name: "Choo Sando", categories: ['japanese', 'sandwiches'], location: 'Central', menu: 'https://chooatx.com/'},
    {name: "Fukumoto", categories: ['japanese', 'fancy'], location: 'East Side', menu: 'http://fukumotoaustin.com/'},
    {name: "Honey Pig BBQ", categories: ['korean'], location: 'North', menu: 'https://www.honeypigbbq.com/austin-tx'},
    {name: "Paik's Noodles (Hmart)", categories: ['korean'], location: 'North', menu: 'https://www.paiksnoodletx.com/menu'},
    {name: "Charm Korean BBQ", categories: ['korean'], location: 'North', menu: 'https://www.charmkoreanbbq.com/'},
    {name: "K-Pub Chicken", categories: ['korean'], location: 'North', menu: 'http://www.kpubatx.com/'},
    {name: "Jan Chi Korean Cuisine & BBQ", categories: ['korean'], location: 'North', menu: 'https://www.janchikoreanbbqtx.com/'},
    {name: "Korean Grill", categories: ['korean'], location: 'North', menu: 'https://koreangrill.wixsite.com/koreangrill'},
    {name: "Seoulju", categories: ['korean'], location: 'North', menu: 'http://www.seouljuatx.com/'},
    {name: "Mom's Taste", categories: ['korean'], location: 'Central', menu: 'http://www.austinbanchan.com/'},
    {name: "Oseyo", categories: ['korean', 'fancy'], location: 'East Side', menu: 'https://www.oseyoaustin.com/'},
    {name: "Underdog", categories: ['korean', 'fancy'], location: 'South 1st/Lamar', menu: 'http://underdog-atx.com/'},
    {name: "Korea House", categories: ['korean'], location: 'North', menu: 'http://koreahouseaustin.com/#menu'},
    {name: "", categories: [], location: '', menu: ''},
    {name: "", categories: [], location: '', menu: ''},
    {name: "", categories: [], location: '', menu: ''},
    {name: "", categories: [], location: '', menu: ''},

    {name: "", categories: [], location: '', menu: ''},

]

export default restaurants